name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-22.04
        #- macos-12
        - macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Install protoc
      run: ./proto-inst.sh
    - name: Check protoc
      run: protoc --version
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
